addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
after_script: npm run coverage
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install moreutils; sudo apt-get install jq; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install moreutils; brew install jq; brew install mysql; brew tap homebrew/services; brew services start mysql; brew services list; fi
  - cd ./src
  - cp ./lib/data/config/config.example.json ./lib/data/config/config.json
  - jq '.sequelize.test.password = null' ./lib/data/config/config.json | sponge ./lib/data/config/config.json
  - mysql -V && mysql -u root -e "CREATE DATABASE karma_test"
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mysql -u root -e "use mysql; update user set plugin='mysql_native_password' where user='root'; flush privileges"; fi
language: node_js
node_js:
  - "node"
os:
  - linux
  - osx
